name: $(Build.DefinitionName) $(date:yyyyMMdd)$(rev:.r)

trigger:
  batch: true
  tags: 
    include:
    - '3.*'
  branches:
    include:
    - '*'

variables:
  BuildPlatform: 'Any CPU'
  BuildConfiguration: 'Release'
  Solution: 'src\PackageReferenceNormalizer.sln'
  isRelease: $[startsWith(variables['Build.SourceBranch'], 'refs/tags/')]

pool:
  vmImage: 'windows-2022'
  demands:
  - msbuild
  - vstest

steps:

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    command: 'restore'
    restoreSolution: '$(Solution)'

- task: MSBuild@1
  displayName: 'Build Solution'
  inputs:
    solution: '$(Solution)'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    clean: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: Packages'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)/Deploy'
    ArtifactName: Packages
